# Generated by Django 4.2.4 on 2023-08-28 13:05

import django_bleach.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "introduction",
                    django_bleach.models.BleachField(blank=True, null=True),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="campaigns/",
                        verbose_name="Featured Image",
                    ),
                ),
            ],
        ),
    ]
