# Generated by Django 4.2.4 on 2023-08-28 13:37

import django.db.models.deletion
import django_bleach.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("campaign", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adventure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "short_description",
                    django_bleach.models.BleachField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Adventure",
                "verbose_name_plural": "Adventures",
            },
        ),
        migrations.CreateModel(
            name="BaseSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("text", django_bleach.models.BleachField(blank=True, null=True)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Base Section",
                "verbose_name_plural": "Base Sections",
                "ordering": ("name",),
            },
        ),
        migrations.AlterModelOptions(
            name="campaign",
            options={"verbose_name": "Campaign", "verbose_name_plural": "Campaigns"},
        ),
        migrations.CreateModel(
            name="Overview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    django_bleach.models.BleachField(blank=True, null=True),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.campaign",
                        verbose_name="Campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overview",
                "verbose_name_plural": "Overviews",
            },
        ),
        migrations.CreateModel(
            name="ImportantNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                ("content", django_bleach.models.BleachField(blank=True, null=True)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Important Note Section",
                "verbose_name_plural": "Important Note Sections",
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    django_bleach.models.BleachField(blank=True, null=True),
                ),
                (
                    "number",
                    models.PositiveIntegerField(default=1, verbose_name="Number"),
                ),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign.adventure",
                        verbose_name="Adventure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chapter",
                "verbose_name_plural": "Chapters",
                "ordering": ("number",),
                "unique_together": {("adventure", "number")},
            },
        ),
        migrations.AddField(
            model_name="adventure",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="campaign.campaign",
                verbose_name="Campaign",
            ),
        ),
        migrations.CreateModel(
            name="SubSection",
            fields=[
                (
                    "basesection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="campaign.basesection",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_sections",
                        to="campaign.basesection",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Section",
                "verbose_name_plural": "Sub Sections",
            },
            bases=("campaign.basesection",),
        ),
        migrations.CreateModel(
            name="OverviewSection",
            fields=[
                (
                    "basesection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="campaign.basesection",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="campaign.overview",
                        verbose_name="Overview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overview Section",
                "verbose_name_plural": "Overview Sections",
            },
            bases=("campaign.basesection",),
        ),
        migrations.CreateModel(
            name="ChapterSection",
            fields=[
                (
                    "basesection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="campaign.basesection",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="campaign.chapter",
                        verbose_name="Chapter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chapter Section",
                "verbose_name_plural": "Chapter Sections",
            },
            bases=("campaign.basesection",),
        ),
    ]
