# Generated by Django 4.2.4 on 2023-08-28 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0002_adventure_basesection_alter_campaign_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adventure",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adventures",
                to="campaign.campaign",
                verbose_name="Campaign",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="adventure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="campaign.adventure",
                verbose_name="Adventure",
            ),
        ),
        migrations.AlterField(
            model_name="overview",
            name="campaign",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="campaign.campaign",
                verbose_name="Campaign",
            ),
        ),
    ]
