# Generated by Django 4.2.4 on 2023-09-02 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaign", "0003_alter_adventure_campaign_alter_chapter_adventure_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("character", "0001_initial"),
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="buildings"),
                ),
                ("name", models.CharField(max_length=255)),
                ("important", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Building",
                "verbose_name_plural": "Buildings",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_capital", models.BooleanField(default=False)),
                ("map", models.ImageField(blank=True, null=True, upload_to="cities")),
                ("name", models.CharField(max_length=255)),
                ("population", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "council",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="character.charactergroup",
                    ),
                ),
                (
                    "guard_force",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities_guarded",
                        to="character.charactergroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Mineral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
            ],
            options={
                "verbose_name": "Mineral",
                "verbose_name_plural": "Minerals",
            },
        ),
        migrations.CreateModel(
            name="ShipWeapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("damage", models.CharField(max_length=20)),
                ("range", models.CharField(max_length=20)),
                ("damage_type", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Weapon",
                "verbose_name_plural": "Weapons",
            },
        ),
        migrations.CreateModel(
            name="Monument",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monument",
                "verbose_name_plural": "Monuments",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Shrine",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shrine",
                "verbose_name_plural": "Shrines",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Stable",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stable",
                "verbose_name_plural": "Stables",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Storehouse",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storehouse",
                "verbose_name_plural": "Storehouses",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Tenement",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenement",
                "verbose_name_plural": "Tenements",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Theater",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Theater",
                "verbose_name_plural": "Theaters",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Tower",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tower",
                "verbose_name_plural": "Towers",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "University",
                "verbose_name_plural": "Universities",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Wall",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wall",
                "verbose_name_plural": "Walls",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Watchtower",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Watchtower",
                "verbose_name_plural": "Watchtowers",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Watermill",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Watermill",
                "verbose_name_plural": "Watermills",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Waterway",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Waterway",
                "verbose_name_plural": "Waterways",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Windmill",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Windmill",
                "verbose_name_plural": "Windmills",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="World",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("map", models.ImageField(blank=True, null=True, upload_to="worlds")),
                ("image", models.ImageField(blank=True, null=True, upload_to="worlds")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worlds",
                        to="campaign.campaign",
                    ),
                ),
                (
                    "dm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worlds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "World",
                "verbose_name_plural": "Worlds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("max_crew_capacity", models.PositiveIntegerField()),
                (
                    "cargo_capacity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "current_cargo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("speed", models.PositiveIntegerField()),
                ("hull_strength", models.PositiveIntegerField()),
                ("location", models.CharField(max_length=100)),
                (
                    "armament",
                    models.ManyToManyField(
                        related_name="equipped_on_ships", to="world.shipweapon"
                    ),
                ),
                (
                    "captain",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="character.character",
                    ),
                ),
                (
                    "crew",
                    models.ManyToManyField(
                        related_name="crewed_ships", to="character.character"
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(related_name="aboard_ships", to="item.item"),
                ),
            ],
            options={
                "verbose_name": "Ship",
                "verbose_name_plural": "Ships",
            },
        ),
        migrations.CreateModel(
            name="NotableEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="notable_events"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "world",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notable_events",
                        to="world.world",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notable Event",
                "verbose_name_plural": "Notable Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Kingdom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("map", models.ImageField(blank=True, null=True, upload_to="kingdoms")),
                ("name", models.CharField(max_length=255)),
                (
                    "army",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kingdoms_army",
                        to="character.charactergroup",
                    ),
                ),
                (
                    "council",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kingdoms_council",
                        to="character.charactergroup",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kingdoms_leader",
                        to="character.character",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kingdoms",
                        to="world.world",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kingdom",
                "verbose_name_plural": "Kingdoms",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="districts"),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="world.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="city",
            name="kingdom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="world.kingdom",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="character.character",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="notable_character_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="notable_character_groups",
                to="character.charactergroup",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="notable_characters",
            field=models.ManyToManyField(
                blank=True, related_name="notable_characters", to="character.character"
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildings",
                to="world.district",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildings",
                to="character.character",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "employees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="workshops_employees",
                        to="character.character",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True, related_name="workshops_items", to="item.item"
                    ),
                ),
            ],
            options={
                "verbose_name": "Workshop",
                "verbose_name_plural": "Workshops",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True, related_name="warehouses", to="item.item"
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="TownHall",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "employees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="town_halls_employees",
                        to="character.character",
                    ),
                ),
                (
                    "rooms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="town_halls_rooms",
                        to="character.character",
                    ),
                ),
            ],
            options={
                "verbose_name": "TownHall",
                "verbose_name_plural": "TownHalls",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Temple",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "gods",
                    models.ManyToManyField(
                        blank=True, related_name="temples", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Temple",
                "verbose_name_plural": "Temples",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Tavern",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "employees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="taverns_employees",
                        to="character.character",
                    ),
                ),
                (
                    "rooms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="taverns_rooms",
                        to="character.character",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tavern",
                "verbose_name_plural": "Taverns",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                ("shop_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "employees",
                    models.ManyToManyField(
                        blank=True, related_name="shops", to="character.character"
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True, related_name="shops", to="item.item"
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop",
                "verbose_name_plural": "Shops",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Quarry",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "mineral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarries",
                        to="world.mineral",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quarry",
                "verbose_name_plural": "Quarries",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Pier",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "ships",
                    models.ManyToManyField(
                        blank=True, related_name="piers", to="world.ship"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pier",
                "verbose_name_plural": "Piers",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Park",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "visitors",
                    models.ManyToManyField(
                        blank=True, related_name="parks", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Park",
                "verbose_name_plural": "Parks",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Palace",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "nobles",
                    models.ManyToManyField(
                        blank=True, related_name="palaces", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Palace",
                "verbose_name_plural": "Palaces",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Monastery",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "monks",
                    models.ManyToManyField(
                        blank=True, related_name="monasteries", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Monastery",
                "verbose_name_plural": "Monasteries",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Mine",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "workers",
                    models.ManyToManyField(
                        blank=True, related_name="mines", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mine",
                "verbose_name_plural": "Mines",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Mill",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "workers",
                    models.ManyToManyField(
                        blank=True, related_name="mills", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mill",
                "verbose_name_plural": "Mills",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True, related_name="markets", to="item.item"
                    ),
                ),
            ],
            options={
                "verbose_name": "Market",
                "verbose_name_plural": "Markets",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Mansion",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "residents",
                    models.ManyToManyField(
                        blank=True, related_name="mansions", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mansion",
                "verbose_name_plural": "Mansions",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Lumberyard",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "lumberjacks",
                    models.ManyToManyField(
                        blank=True, related_name="lumberyards", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lumberyard",
                "verbose_name_plural": "Lumberyards",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Lighthouse",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "keepers",
                    models.ManyToManyField(
                        blank=True, related_name="lighthouses", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lighthouse",
                "verbose_name_plural": "Lighthouses",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "books",
                    models.ManyToManyField(
                        blank=True, related_name="libraries", to="item.item"
                    ),
                ),
            ],
            options={
                "verbose_name": "Library",
                "verbose_name_plural": "Libraries",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Inn",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "employees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="inns_employees",
                        to="character.character",
                    ),
                ),
                (
                    "rooms",
                    models.ManyToManyField(
                        blank=True, related_name="inns_rooms", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Inn",
                "verbose_name_plural": "Inns",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Guildhall",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "guildmasters",
                    models.ManyToManyField(
                        blank=True, related_name="guildhalls", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Guildhall",
                "verbose_name_plural": "Guildhalls",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="GuardPost",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "guards",
                    models.ManyToManyField(
                        blank=True, related_name="guard_posts", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Guard Post",
                "verbose_name_plural": "Guard Posts",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Granary",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True, related_name="granaries", to="item.item"
                    ),
                ),
            ],
            options={
                "verbose_name": "Granary",
                "verbose_name_plural": "Granaries",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Gatehouse",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "guards",
                    models.ManyToManyField(
                        blank=True, related_name="gatehouses", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gatehouse",
                "verbose_name_plural": "Gatehouses",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Garden",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "gardeners",
                    models.ManyToManyField(
                        blank=True, related_name="gardens", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Garden",
                "verbose_name_plural": "Gardens",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Fort",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "soldiers",
                    models.ManyToManyField(
                        blank=True, related_name="forts", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fort",
                "verbose_name_plural": "Forts",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "workers",
                    models.ManyToManyField(
                        blank=True, related_name="farms", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm",
                "verbose_name_plural": "Farms",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Courthouse",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "judges",
                    models.ManyToManyField(
                        blank=True, related_name="courthouses", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Courthouse",
                "verbose_name_plural": "Courthouses",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Church",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "priests",
                    models.ManyToManyField(
                        blank=True, related_name="churches", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Church",
                "verbose_name_plural": "Churches",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Castle",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "nobles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="castles_nobles",
                        to="character.character",
                    ),
                ),
                (
                    "soldiers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="castles_soldiers",
                        to="character.character",
                    ),
                ),
            ],
            options={
                "verbose_name": "Castle",
                "verbose_name_plural": "Castles",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Carpenter",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True, related_name="carpenters", to="item.item"
                    ),
                ),
            ],
            options={
                "verbose_name": "Carpenter",
                "verbose_name_plural": "Carpenters",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Brothel",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "prostitutes",
                    models.ManyToManyField(
                        blank=True, related_name="brothels", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Brothel",
                "verbose_name_plural": "Brothels",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Blacksmith",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "employees",
                    models.ManyToManyField(
                        blank=True, related_name="blacksmiths", to="character.character"
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True, related_name="blacksmiths", to="item.item"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blacksmith",
                "verbose_name_plural": "Blacksmiths",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Bazaar",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        blank=True, related_name="bazaars", to="item.item"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bazaar",
                "verbose_name_plural": "Bazaars",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Bathhouse",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "employees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bathhouses_employees",
                        to="character.character",
                    ),
                ),
                (
                    "rooms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bathhouses_rooms",
                        to="character.character",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bathhouse",
                "verbose_name_plural": "Bathhouses",
            },
            bases=("world.building",),
        ),
        migrations.CreateModel(
            name="Barracks",
            fields=[
                (
                    "building_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="world.building",
                    ),
                ),
                (
                    "soldiers",
                    models.ManyToManyField(
                        blank=True, related_name="barracks", to="character.character"
                    ),
                ),
            ],
            options={
                "verbose_name": "Barracks",
                "verbose_name_plural": "Barracks",
            },
            bases=("world.building",),
        ),
    ]
