# Generated by Django 4.2.4 on 2023-09-02 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("character", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("armor_class", models.PositiveIntegerField(blank=True, null=True)),
                ("base_item", models.CharField(blank=True, max_length=255, null=True)),
                ("damage", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "damage_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("acid", "Acid"),
                            ("bludgeoning", "Bludgeoning"),
                            ("cold", "Cold"),
                            ("fire", "Fire"),
                            ("force", "Force"),
                            ("lightning", "Lightning"),
                            ("necrotic", "Necrotic"),
                            ("piercing", "Piercing"),
                            ("poison", "Poison"),
                            ("psychic", "Psychic"),
                            ("radiant", "Radiant"),
                            ("slashing", "Slashing"),
                            ("thunder", "Thunder"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("duration", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "duration_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("instantaneous", "Instantaneous"),
                            ("round", "Round"),
                            ("minute", "Minute"),
                            ("hour", "Hour"),
                            ("day", "Day"),
                            ("week", "Week"),
                            ("month", "Month"),
                            ("year", "Year"),
                            ("permanent", "Permanent"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="items")),
                ("magic_item", models.BooleanField(default=False)),
                ("max_charges", models.PositiveIntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("price", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "price_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cp", "Copper"),
                            ("sp", "Silver"),
                            ("ep", "Electrum"),
                            ("gp", "Gold"),
                            ("pp", "Platinum"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("range", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "rarity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("very_rare", "Very Rare"),
                            ("legendary", "Legendary"),
                            ("artifact", "Artifact"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("recharge_rate", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "recharge_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("instantaneous", "Instantaneous"),
                            ("round", "Round"),
                            ("minute", "Minute"),
                            ("hour", "Hour"),
                            ("day", "Day"),
                            ("week", "Week"),
                            ("month", "Month"),
                            ("year", "Year"),
                            ("permanent", "Permanent"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("requires_attunement", models.BooleanField(default=False)),
                ("save_dc", models.PositiveIntegerField(blank=True, null=True)),
                ("type", models.CharField(max_length=255)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
            },
        ),
        migrations.CreateModel(
            name="ItemProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Item Property",
                "verbose_name_plural": "Item Properties",
            },
        ),
        migrations.CreateModel(
            name="ItemTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traits",
                        to="item.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Trait",
                "verbose_name_plural": "Item Traits",
            },
        ),
        migrations.CreateModel(
            name="ItemModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modifies", models.CharField(max_length=255)),
                ("amount", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("bonus", "Bonus"), ("penalty", "Penalty")],
                        max_length=255,
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifier",
                        to="item.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Modifier",
                "verbose_name_plural": "Item Modifiers",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="properties",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="item.itemproperty"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="save_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="character.abilityscore",
            ),
        ),
    ]
