# Generated by Django 4.2.4 on 2023-09-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weapon", "Weapon"),
                    ("armor", "Armor"),
                    ("consumable", "Consumable"),
                    ("tool", "Tool"),
                    ("adventuring_gear", "Adventuring Gear"),
                    ("mounts_and_vehicles", "Mounts and Vehicles"),
                    ("trade_goods", "Trade Goods"),
                    ("magic_item", "Magic Item"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
