# Generated by Django 4.2.4 on 2023-09-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbilityScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Ability Score",
                "verbose_name_plural": "Ability Scores",
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                ("level", models.IntegerField(verbose_name="Level")),
            ],
        ),
        migrations.CreateModel(
            name="CharacterGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("total_members", models.IntegerField(default=0)),
                (
                    "emblem",
                    models.ImageField(blank=True, null=True, upload_to="emblems/"),
                ),
                (
                    "allies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="allies_groups",
                        to="character.charactergroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Group",
                "verbose_name_plural": "Character Groups",
            },
        ),
    ]
